# Generated by Django 5.2.8 on 2025-12-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignment_assigned_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["-assigned_date"],
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="fine_paid_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending Proof", "Pending Proof"),
                    ("Proof Submitted", "Proof Submitted"),
                    ("Paid/Approved", "Paid/Approved"),
                    ("Denied/Reopen", "Denied/Reopen"),
                ],
                default="Pending Proof",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="fine_proof_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
