# Generated by Django 5.2.8 on 2025-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned')], default='Available', max_length=20),
        ),
    ]
