"""
Django settings for finalproject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(&=*&ci7=wx&!iznmr&hf#wvlj)n@t+c)ydj%@b^pmpcdobnfj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    "https://communicatory-trena-hypersentimentally.ngrok-free.dev",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'assets',              # New App
    'organizations',       # New App
    'org_settings',        # New App
    'users',               # New App
    'departments',         # New App
    'asset_categories',    # New App
    'assignments',         # New App
    'assignment_history',
    # 'simple-jwt',
    # Swagger/OpenAPI
    'drf_spectacular',
    'api',
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
     # React dev server


ROOT_URLCONF = 'finalproject.urls'

# settings.py

import os

# Assuming BASE_DIR is defined like this (adjust if yours is different)
# If using Django 4.0+
BASE_DIR = Path(__file__).resolve().parent.parent
# If using older Django:
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # --- CORRECTED LINE BELOW ---
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # --- END OF CORRECTION ---
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finalproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'users.User'
AUTH_USER_MODEL = 'users.User'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
   'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

AUTH_USER_MODEL = 'users.User'

SIMPLE_JWT = {
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}



# SPECTACULAR SETTINGS (OpenAPI/Swagger)
SPECTACULAR_SETTINGS = {
    # REQUIRED: TITTLE for the documentation site
    'TITLE': 'Asset Tracking API',
    
    # OPTIONAL: Description of the project
    'DESCRIPTION': 'Multi-Tenant Asset Tracking and Management System API.',
    
    # OPTIONAL: Version number
    'VERSION': '1.0.0',
    
    # OPTIONAL: Schema file format (YAML, JSON)
    'SERVE_INCLUDE_SCHEMA': False,  # True by default, but we serve it separately
    
    # OPTIONAL: Customize where the base ViewSets are located
    'COMPONENT_SPLIT_REQUEST': True, # Reduces generated file size for large projects

    # OPTIONAL: AUTHENTICATION (For Swagger UI's "Authorize" button)
    # This configuration is CRITICAL for JWT to work in Swagger UI
    'SECURITY': [
        {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    ],
}


import os

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # This ensures it's a string
MEDIA_URL = '/media/'
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB, adjust as needed

