# Generated by Django 5.2.8 on 2025-11-20 09:32

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateField(default=assignments.models.get_today),
        ),
    ]
