# from django.urls import path, include
# from rest_framework.routers import DefaultRouter

# # Import all ViewSets from the centralized core_api app
# from api.views import (
#     OrganizationViewSet,
#     OrgSettingsViewSet,
#     UserViewSet,
#     DepartmentViewSet,
#     AssetCategoryViewSet,
#     AssetViewSet,
#     AssignmentViewSet,
#     AssignmentHistoryViewSet
# )

# # Initialize the primary API router
# router = DefaultRouter()

# # Register all the ViewSets with the router
# # Base URLs will be: /organizations/, /users/, /assets/, etc.
# router.register(r'organizations', OrganizationViewSet)
# router.register(r'org-settings', OrgSettingsViewSet, basename='org-settings') 
# router.register(r'users', UserViewSet)
# router.register(r'departments', DepartmentViewSet)
# router.register(r'asset-categories', AssetCategoryViewSet)
# router.register(r'assets', AssetViewSet)
# router.register(r'assignments', AssignmentViewSet)
# router.register(r'assignment-history', AssignmentHistoryViewSet)

# # The urlpatterns combine the dedicated setup endpoint and the router-generated endpoints
# urlpatterns = [
#     # 1. Public, unauthenticated endpoint for initial setup (e.g., /api/v1/setup/)
#     path('', include('initial_setup.urls')), 

#     # 2. Authenticated API endpoints (all resources managed by the router)
#     path('', include(router.urls)),
# ]



from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import all ViewSets AND the necessary InitialSetupView from the local views.py
from .views import (
    OrganizationViewSet,
    OrgSettingsViewSet,
    UserViewSet,
    DepartmentViewSet,
    AssetCategoryViewSet,
    AssetViewSet,
    AssignmentViewSet,
    AssignmentHistoryViewSet,
    InitialSetupView
)

# Initialize the primary API router for all authenticated endpoints
router = DefaultRouter()

# Register all the ViewSets with the router
router.register(r'organizations', OrganizationViewSet)
router.register(r'org-settings', OrgSettingsViewSet, basename='org-settings') 
router.register(r'users', UserViewSet)
router.register(r'departments', DepartmentViewSet)
router.register(r'asset-categories', AssetCategoryViewSet)
router.register(r'assets', AssetViewSet)
router.register(r'assignments', AssignmentViewSet)
router.register(r'assignment-history', AssignmentHistoryViewSet)

# The urlpatterns combine the dedicated setup endpoint and the router-generated endpoints
urlpatterns = [
    # 1. Public, unauthenticated endpoint for initial setup (e.g., /api/v1/setup/)
    # Uses the InitialSetupView class imported from the local views.py
    path('setup/', InitialSetupView.as_view(), name='initial-setup'), 

    # 2. Authenticated API endpoints (all resources managed by the router)
    # Includes all routes generated by the DefaultRouter (users/, assets/, etc.)
    path('', include(router.urls)),
]